# Generated by Django 3.2.25 on 2025-01-24 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='用户编号'),
        ),
    ]
