# Generated by Django 4.2.19 on 2025-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='地址'),
        ),
    ]
