# Generated by Django 4.2.19 on 2025-04-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_pinlun"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pinlun", options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
    ]
