# Generated by Django 3.2.25 on 2025-01-24 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='信息标题')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='信息内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_user', to='user.userinfo', verbose_name='催发用户')),
            ],
            options={
                'verbose_name': '催发信息',
                'verbose_name_plural': '催发信息',
            },
        ),
    ]
