# Generated by Django 3.2.25 on 2025-01-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='单词')),
                ('fanyi', models.CharField(max_length=20, verbose_name='翻译')),
                ('type', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类'), (4, '四级分类')], verbose_name='类型')),
                ('liju', models.CharField(max_length=20, verbose_name='例句')),
                ('liju_fanyi', models.CharField(max_length=20, verbose_name='例句翻译')),
            ],
            options={
                'verbose_name': '词库',
                'verbose_name_plural': '词库',
            },
        ),
    ]
