# Generated by Django 4.2.19 on 2025-04-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesaurus',
            name='type',
            field=models.IntegerField(choices=[(1, '雅思词汇'), (2, '托福词汇'), (3, 'RGE词汇'), (4, 'GMAT词汇')], verbose_name='类型'),
        ),
    ]
