# Generated by Django 3.2.25 on 2025-01-24 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('30da493b-52f7-4009-a9fd-a64c35704693'), max_length=255, verbose_name='文章编号'),
        ),
    ]
