# Generated by Django 3.2.25 on 2025-01-24 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5eb0c003-deb7-46cd-a889-86a96a579c8b'), max_length=255, verbose_name='文章编号'),
        ),
    ]
