# Generated by Django 3.2.25 on 2025-01-24 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1f7f1d8d-0852-47e6-b872-83b9c684effe'), max_length=255, verbose_name='文章编号'),
        ),
    ]
