# Generated by Django 4.2.19 on 2025-02-26 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content_fanyi',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容翻译'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_fanyi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文章标题翻译'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2e0bf35f-33e5-4c55-b457-6c3e079de277'), max_length=255, verbose_name='文章编号'),
        ),
    ]
