# Generated by Django 4.2.19 on 2025-02-26 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_content_fanyi_articles_title_fanyi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2a5c1a91-67f8-4e86-8f56-e7afcbf6ad82'), max_length=255, verbose_name='文章编号'),
        ),
    ]
