# Generated by Django 4.2.19 on 2025-02-26 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('788758e3-dd90-4088-9a1d-ebaf98b6fadd'), max_length=255, verbose_name='文章编号'),
        ),
    ]
