# Generated by Django 4.2.19 on 2025-02-27 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('aa53f14f-69ed-4686-b240-6781a768717b'), max_length=255, verbose_name='文章编号'),
        ),
    ]
