# Generated by Django 4.2.19 on 2025-04-24 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c52546a2-b1f0-41df-bebe-81eabcfebbc1'), max_length=255, verbose_name='文章编号'),
        ),
    ]
