# Generated by Django 4.2.19 on 2025-04-24 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articles_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='uuid',
            field=models.CharField(default=uuid.UUID('291413e3-2cea-4301-af3f-30595ada210f'), max_length=255, verbose_name='文章编号'),
        ),
    ]
