# Generated by Django 4.2.19 on 2025-04-25 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_alter_articles_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="uuid",
            field=models.CharField(
                default=uuid.UUID("5605f52c-448d-48bb-bd60-c959515aadc7"),
                max_length=255,
                verbose_name="文章编号",
            ),
        ),
    ]
