# Generated by Django 3.2.25 on 2025-01-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True, verbose_name='题目')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='题目创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='生效')),
                ('question_type', models.IntegerField(choices=[(1, '听力'), (2, '阅读理解')], default=2, verbose_name='题目类型')),
            ],
            options={
                'verbose_name': '题库题目',
                'verbose_name_plural': '题库题目',
            },
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150, verbose_name='选项')),
                ('correct_option', models.BooleanField(default=False, verbose_name='答案')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_questions', to='app.question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '问题选项',
                'verbose_name_plural': '问题选项',
            },
        ),
    ]
