# Generated by Django 3.2.25 on 2025-01-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tingliQuestion',
            fields=[
            ],
            options={
                'verbose_name': '听力题库',
                'verbose_name_plural': '听力题库',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.question',),
        ),
        migrations.CreateModel(
            name='yueduQuestion',
            fields=[
            ],
            options={
                'verbose_name': '阅读理解题库',
                'verbose_name_plural': '阅读理解题库',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.question',),
        ),
    ]
