# Generated by Django 4.2.19 on 2025-02-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_uuid'),
        ('app', '0002_tingliquestion_yueduquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
                ('create_data', models.DateField(auto_now=True, verbose_name='日期')),
                ('numbers', models.IntegerField(default=1, verbose_name='次数')),
                ('choose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_choose', to='app.choose', verbose_name='问题选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_question_id', to='app.question', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_user_phone', to='user.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
            },
        ),
    ]
